### ISSUE TITLE
FileNotFoundError: No such file or directory (os error 2): data/processed/commanders.parquet

### ISSUE THREAD

**Issue by dabricksta** [DaveParr/mtgai#4]
~Be gentle, this is my first time using GitHub/creating an issue/contributing to OSS/etc.!~

When running `make app`, http://localhost:8502/ displays the titled error. Not sure if there is set-up required outside of what the makefile executes - I am happy to contribute to update :)

Cheers @DaveParr !

**Comment by DaveParr** [comment]
There is!

Totally a failure of documentation. `README.MD` should include a number of setup steps. In our DMs I had forgotten one of them.

I think the process should currently be:

1. Clone this repo locally
2. Setup `.env` file locally
3. Run `make data` to create `data/processed/commanders.parquet`
4. Run `make app` to create a streamlit app session

@dabricksta did you manage to workout how to create a suitable .env file? I don't think that's documented yet either.

**Comment by dabricksta** [comment]
Not quite! `OPEN_AI_KEY` is supposed to be a string, right? eg. ```OPENAI_API_KEY='sk-...'``` with single quotes. I've tried it with both personal and project api keys, no luck so far.

Right now `make data` gets me to:

```
File "/opt/anaconda3/envs/mtgai/lib/python3.11/site-packages/openai/_base_client.py", line 1041, in _request
raise self._make_status_error_from_response(err.response) from None
openai.AuthenticationError: Error code: 401 - {'error': {'message': 'Incorrect API key provided: sk-a0Dd0***********************************************************************************koQA. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}
make: *** [vectorstore] Error 1
```

edit: well darn, now I'm seeing:
```openai.AuthenticationError: Error code: 401 - {'error': {'message': 'OpenAI-Organization header should match organization for API key', 'type': 'invalid_request_error', 'param': None, 'code': 'mismatched_organization'}}```

I've created a branch called `user-2` to collect the fixes as we get me set up using it, but I don't have permission to push yet 🥹

**Comment by DaveParr** [comment]
Yes, so the organisation key I forgot about. It's a bad hack I accepted for a bit then forgot about. It's to do with how I was generating my own API keys via the company I had set up at the time: https://platform.openai.com/docs/guides/production-best-practices/setting-up-your-organization. This project should likely not have any requirements for an organisational API key. That should be a change to the codebase expectations.

@dabricksta So if you're keen to contribute to the project, it works a little differently on GitHub than we do at work. Am I right that you've cloned this repo down to your local and done the work there?

The steps for GitHub OpenSource stuff is usually the following:

1. _Fork_ this repository with the button at the top right to your user account space.
2. _Clone the fork_  from your user space in GitHub to your local machine
3. Make the changes in your local machine in a feature branch
4. Push the changes in your local machine to _your fork_
5. Open a PR in the GitHub UI across forks from your feature branch to this develop branch.

[Here is some extra guidance](https://opensource.guide/how-to-contribute/#opening-a-pull-request)

**Comment by DaveParr** [comment]
@dabricksta I think I've just worked it out. The var is a string, but a bare one, no quote in the .env file, e.g.
`OPENAI_API_KEY=sk-..`

but not `OPENAI_API_KEY="sk-.."` or `OPENAI_API_KEY='sk-..'`. Hope we got it 🤞🏻

**Comment by dabricksta** [comment]
Right, yeah that makes sense.

I'm still a bit confused on how to use OpenAI's newer paradigm of organization + project keys instead of just api keys in terms of set-up here. I think some 1:1 would be helpful!

LMK if you'd prefer to chat over Slack or something else entirely. Cheers!

**Comment by DaveParr** [comment]
So I've got myself confused now. I think I'm able to run it _without_ the ORGANIZATION_ID value set. OpenAI made a lot of rapid changes to their system over the start of last year about how API keys worked, and langchain also made a number of changes. Going to dig into it more now.

**Comment by dabricksta** [comment]
Hm, I still can't get past `make data`:

```openai.AuthenticationError: Error code: 401 - {'error': {'message': 'OpenAI-Organization header should match organization for API key', 'type': 'invalid_request_error', 'param': None, 'code': 'mismatched_organization'}}```

My .env set-up is
```
OPENAI_API_KEY=sk-proj-...
OPENAI_ORG_ID=org-....
LANGCHAIN_PROJECT=mtgai
LANGCHAIN_API_KEY=lsv2....
LANGCHAIN_TRACING_V2=True```

**Comment by DaveParr** [comment]
@dabricksta I'll jump in discord in a few
